//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestingSystem.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string BTN_Apply {
            get {
                return ResourceManager.GetString("BTN_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к попыткам.
        /// </summary>
        public static string BTN_BackToAttempts {
            get {
                return ResourceManager.GetString("BTN_BackToAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к тестам.
        /// </summary>
        public static string BTN_BackToTests {
            get {
                return ResourceManager.GetString("BTN_BackToTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к темам.
        /// </summary>
        public static string BTN_BackToThemes {
            get {
                return ResourceManager.GetString("BTN_BackToThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string BTN_Cancel {
            get {
                return ResourceManager.GetString("BTN_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить попытку.
        /// </summary>
        public static string BTN_ContinueAttempt {
            get {
                return ResourceManager.GetString("BTN_ContinueAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        public static string BTN_Create {
            get {
                return ResourceManager.GetString("BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать вопрос.
        /// </summary>
        public static string BTN_CreateQuestion {
            get {
                return ResourceManager.GetString("BTN_CreateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать тест.
        /// </summary>
        public static string BTN_CreateTest {
            get {
                return ResourceManager.GetString("BTN_CreateTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать тему.
        /// </summary>
        public static string BTN_CreateTheme {
            get {
                return ResourceManager.GetString("BTN_CreateTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string BTN_Delete {
            get {
                return ResourceManager.GetString("BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закончить тест.
        /// </summary>
        public static string BTN_EndTest {
            get {
                return ResourceManager.GetString("BTN_EndTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string BTN_LogOn {
            get {
                return ResourceManager.GetString("BTN_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string BTN_Register {
            get {
                return ResourceManager.GetString("BTN_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть результаты.
        /// </summary>
        public static string BTN_SeeResult {
            get {
                return ResourceManager.GetString("BTN_SeeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать новую попытку.
        /// </summary>
        public static string BTN_StartNewAttempt {
            get {
                return ResourceManager.GetString("BTN_StartNewAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введены некорректные данные.
        /// </summary>
        public static string ERROR_IncorrectData {
            get {
                return ResourceManager.GetString("ERROR_IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином уже существует!.
        /// </summary>
        public static string ERROR_LoginExists {
            get {
                return ResourceManager.GetString("ERROR_LoginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос содержится в тодном из тестов! Удалите тест!.
        /// </summary>
        public static string ERROR_QuestionContainsInTest {
            get {
                return ResourceManager.GetString("ERROR_QuestionContainsInTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой вопрос уже существует в теме!.
        /// </summary>
        public static string ERROR_QuestionExists {
            get {
                return ResourceManager.GetString("ERROR_QuestionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос должен содержать хотя бы один верный ответ!.
        /// </summary>
        public static string ERROR_QuestionMustContainRightAnswers {
            get {
                return ResourceManager.GetString("ERROR_QuestionMustContainRightAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест с таким именем уже существует!.
        /// </summary>
        public static string ERROR_TestExists {
            get {
                return ResourceManager.GetString("ERROR_TestExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест должен содержать хотя бы один вопрос!.
        /// </summary>
        public static string ERROR_TestMustContainQuestions {
            get {
                return ResourceManager.GetString("ERROR_TestMustContainQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема содержится в одном из тестов! Удалите тест!.
        /// </summary>
        public static string ERROR_ThemeContainsInTest {
            get {
                return ResourceManager.GetString("ERROR_ThemeContainsInTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема с таким именем уже существует!.
        /// </summary>
        public static string ERROR_ThemeExists {
            get {
                return ResourceManager.GetString("ERROR_ThemeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль!.
        /// </summary>
        public static string ERROR_WrongPassword {
            get {
                return ResourceManager.GetString("ERROR_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст ответа.
        /// </summary>
        public static string FIELD_AnswerText {
            get {
                return ResourceManager.GetString("FIELD_AnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер попытки.
        /// </summary>
        public static string FIELD_AttemptNumber {
            get {
                return ResourceManager.GetString("FIELD_AttemptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество попыток.
        /// </summary>
        public static string FIELD_AttemptsCount {
            get {
                return ResourceManager.GetString("FIELD_AttemptsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string FIELD_FirstName {
            get {
                return ResourceManager.GetString("FIELD_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верный.
        /// </summary>
        public static string FIELD_IsCorrect {
            get {
                return ResourceManager.GetString("FIELD_IsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string FIELD_LastName {
            get {
                return ResourceManager.GetString("FIELD_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string FIELD_Login {
            get {
                return ResourceManager.GetString("FIELD_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string FIELD_Password {
            get {
                return ResourceManager.GetString("FIELD_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очки.
        /// </summary>
        public static string FIELD_Points {
            get {
                return ResourceManager.GetString("FIELD_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество вопросов.
        /// </summary>
        public static string FIELD_QuestionsCount {
            get {
                return ResourceManager.GetString("FIELD_QuestionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст вопроса.
        /// </summary>
        public static string FIELD_QuestionText {
            get {
                return ResourceManager.GetString("FIELD_QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во верных ответов.
        /// </summary>
        public static string FIELD_QuestionType {
            get {
                return ResourceManager.GetString("FIELD_QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осталось попыток.
        /// </summary>
        public static string FIELD_RemainingAttempts {
            get {
                return ResourceManager.GetString("FIELD_RemainingAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повтор пароля.
        /// </summary>
        public static string FIELD_RepeatPassword {
            get {
                return ResourceManager.GetString("FIELD_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат.
        /// </summary>
        public static string FIELD_Score {
            get {
                return ResourceManager.GetString("FIELD_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название теста.
        /// </summary>
        public static string FIELD_TestName {
            get {
                return ResourceManager.GetString("FIELD_TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название темы.
        /// </summary>
        public static string FIELD_ThemeName {
            get {
                return ResourceManager.GetString("FIELD_ThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Затраченное время (мин.).
        /// </summary>
        public static string FIELD_Time {
            get {
                return ResourceManager.GetString("FIELD_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время на выполнение (мин.).
        /// </summary>
        public static string FIELD_TimeLimit {
            get {
                return ResourceManager.GetString("FIELD_TimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string FIELD_UserName {
            get {
                return ResourceManager.GetString("FIELD_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка #.
        /// </summary>
        public static string MES_Attempt {
            get {
                return ResourceManager.GetString("MES_Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общий рейтинг.
        /// </summary>
        public static string MES_CommonRating {
            get {
                return ResourceManager.GetString("MES_CommonRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать вопрос.
        /// </summary>
        public static string MES_CreateQuestion {
            get {
                return ResourceManager.GetString("MES_CreateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать тему.
        /// </summary>
        public static string MES_CreateTheme {
            get {
                return ResourceManager.GetString("MES_CreateTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите текст ответа.
        /// </summary>
        public static string MES_EnterAnswerText {
            get {
                return ResourceManager.GetString("MES_EnterAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин и пароль.
        /// </summary>
        public static string MES_EnterLoginAndPassword {
            get {
                return ResourceManager.GetString("MES_EnterLoginAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите текст вопроса.
        /// </summary>
        public static string MES_EnterQuestionText {
            get {
                return ResourceManager.GetString("MES_EnterQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрано.
        /// </summary>
        public static string MES_IsSelected {
            get {
                return ResourceManager.GetString("MES_IsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осталось времени.
        /// </summary>
        public static string MES_RemainingTime {
            get {
                return ResourceManager.GetString("MES_RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат.
        /// </summary>
        public static string MES_Result {
            get {
                return ResourceManager.GetString("MES_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по вопросам.
        /// </summary>
        public static string MES_SearchQuestion {
            get {
                return ResourceManager.GetString("MES_SearchQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по тестам.
        /// </summary>
        public static string MES_SearchTest {
            get {
                return ResourceManager.GetString("MES_SearchTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по темам.
        /// </summary>
        public static string MES_SearchTheme {
            get {
                return ResourceManager.GetString("MES_SearchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по темам и вопросам.
        /// </summary>
        public static string MES_SearchThemeAndQuestion {
            get {
                return ResourceManager.GetString("MES_SearchThemeAndQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по пользователям.
        /// </summary>
        public static string MES_SearchUser {
            get {
                return ResourceManager.GetString("MES_SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопросы теста.
        /// </summary>
        public static string MES_TestQuestions {
            get {
                return ResourceManager.GetString("MES_TestQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string TITLE_Error {
            get {
                return ResourceManager.GetString("TITLE_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная страница.
        /// </summary>
        public static string TITLE_HomePage {
            get {
                return ResourceManager.GetString("TITLE_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string TITLE_LogOff {
            get {
                return ResourceManager.GetString("TITLE_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string TITLE_LogOn {
            get {
                return ResourceManager.GetString("TITLE_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои попытки.
        /// </summary>
        public static string TITLE_MyAttempts {
            get {
                return ResourceManager.GetString("TITLE_MyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тесты пользователя.
        /// </summary>
        public static string TITLE_MyTests {
            get {
                return ResourceManager.GetString("TITLE_MyTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейтинг.
        /// </summary>
        public static string TITLE_Rating {
            get {
                return ResourceManager.GetString("TITLE_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string TITLE_Register {
            get {
                return ResourceManager.GetString("TITLE_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение теста.
        /// </summary>
        public static string TITLE_RunTest {
            get {
                return ResourceManager.GetString("TITLE_RunTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест.
        /// </summary>
        public static string TITLE_Test {
            get {
                return ResourceManager.GetString("TITLE_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание теста.
        /// </summary>
        public static string TITLE_TestCreating {
            get {
                return ResourceManager.GetString("TITLE_TestCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты попытки.
        /// </summary>
        public static string TITLE_TestSessionResults {
            get {
                return ResourceManager.GetString("TITLE_TestSessionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список тестов.
        /// </summary>
        public static string TITLE_TestsList {
            get {
                return ResourceManager.GetString("TITLE_TestsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема.
        /// </summary>
        public static string TITLE_Theme {
            get {
                return ResourceManager.GetString("TITLE_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список тем.
        /// </summary>
        public static string TITLE_ThemesList {
            get {
                return ResourceManager.GetString("TITLE_ThemesList", resourceCulture);
            }
        }
    }
}
